const LOCALSTORAGE_USER_DATA_KEY = "user";
const LOCALSTORAGE_MEMBER_DATA_KEY = "member";
const LOCALSTORAGE_TASK_DATA_KEY = "task";

export {
  LOCALSTORAGE_USER_DATA_KEY,
  LOCALSTORAGE_MEMBER_DATA_KEY,
  LOCALSTORAGE_TASK_DATA_KEY
};
